### ISSUE TITLE
Suggestion:  Add 'developer' mode which has a card pre-inputted into the program

### ISSUE THREAD

**Issue by OBlount** [Thetvdh/CardValidator#12]
Getting tired of inputting 1234123412341234 and 666 as the CSV.

Think it would be good for the workflow to have a pre-inputted card in the program.

**Comment by Thetvdh** [comment]
Added developer card. Either change DEBUG to TRUE or enter 0 in the first options menu.

If ever compiled as a proper program, remove these features as part of the prod.
