### ISSUE TITLE
Update date checks to allow for 2022 issue dates.

### ISSUE THREAD

**Issue by Thetvdh** [Thetvdh/CardValidator#16]
Self explanatory. Potentially put these into variables so we don't have to go fishing around for them :).

**Comment by OBlount** [comment]
Do we go one step further and use the OS's date?

**Comment by OBlount** [comment]
Perhaps using [this](https://www.tutorialspoint.com/c_standard_library/c_function_ctime.htm)

**Comment by Thetvdh** [comment]
Done.
