### ISSUE TITLE
Implement Luhn algorithm to accurately validate Visa (and perhaps MasterCard).

### ISSUE THREAD

**Issue by OBlount** [Thetvdh/CardValidator#6]
[Luhn](https://www.freeformatter.com/credit-card-number-generator-validator.html) Formula is just a bit of maths to validate a card number.

Plus, Visa (and other cards) sometimes start with a particular sequence of numbers. The number validation should also validate that aspect too.

**Comment by Thetvdh** [comment]
30/12/2021 Begun wor on Luhn implementation

**Comment by OBlount** [comment]
Respect

**Comment by Thetvdh** [comment]
Luhn Algorithm implemented in commit 0631eb77660d3d0647e9c2369084f03121d4d9c4.
