### ISSUE TITLE
Program crashes when more than one card in the linked list while running in terminal environment

### ISSUE THREAD

**Issue by Thetvdh** [Thetvdh/CardValidator#8]
When running in CLion the program works perfectly however when running in a non CLion environment it exits out of the program when running in either CMD or Powershell. Issue only occurs when more than one card is in the linked list. Potentially an issue with the last node in the list?

**Comment by OBlount** [comment]
Works alright in my environment. Doesn't exit 'randomly'.

**Comment by OBlount** [comment]
Your best bet is to revert to a previous working commit and drop lines one by one till the crashing occurs.

**Comment by Thetvdh** [comment]
> Works alright in my environment. Doesn't exit 'randomly'.

Is this in a Windows or Linux environment?

**Comment by OBlount** [comment]
Linux!

**Comment by Thetvdh** [comment]
Works on Ubuntu, Arch, and CLion runtime envrionments. Does not work in Powershell or CMD. Works with one item in the linked list, does not work with 2, works with more than 2.

**Comment by Thetvdh** [comment]
Fixed in commit 1c15141e4a2246dd208f9854ca3b9dc1a8434e1b

When adding the second item to the linked list the pNewCard->next was undefined and pointing to random data. Added a NULL pointer and all seems fine.
